spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
  redis:
    host: 192.168.2.150
    port: 6379
    password:
logicserver:
  name: niuniu
  connector: hallserver
jwt:
  secret: ASDF1234a
  expiration: 120000