logging:
  level:
    root: info
spring:
  data:
    mongodb:
      host: 106.13.39.143
      port: 27017
      database: mywuwu
  redis:
    host: 106.13.39.143
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 100ms
hall:
  routes:
    1: hallserver
    2: yingsanzhang
    3: paodekuai
    4: baijiale
    5: niuniu
  name: hallserver
netty-websocket:
  host: 192.168.3.6
  port: 8083
  path: /hall
jwt:
  secret: ASDF1234a
  expiration: 120000