spring:
  data:
    mongodb:
      host: 106.13.39.143
      port: 27017
      database: mywuwu
  redis:
    host: 106.13.39.143
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 500ms
game:
  servers:
    - ip: 192.168.2.198
      port: 8083
      name: 游戏服务器
      path: hall
    - ip: localhost
      port: 8083
      name: 服务器2
      path: hall
jwt:
  secret: ASDF1234a
  expiration: 120000