spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: 192.168.2.150
    port: 6379
    password:
game:
  servers:
    - ip: localhost
      port: 8083
      name: 服务器1
      path: hall
    - ip: localhost
      port: 8083
      name: 服务器2
      path: hall
jwt:
  secret: ASDF1234a
  expiration: 120000